# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

expand-or-complete-with-dots() {      # This bunch of code displays red dots when autocompleting
  echo -n "\e[31m......\e[0m"         # a command with the tab key, "Oh-my-zsh"-style.
  zle expand-or-complete
  zle redisplay
}
zle -N expand-or-complete-with-dots
bindkey "^I" expand-or-complete-with-dots

#disable auto correct
unsetopt correct
#disable verify
setopt rm_star_silent clobber
unalias rm &>/dev/null
unalias cp &>/dev/null
unalias mv &>/dev/null

if [ -f ~/.sharedrc ]; then
  source ~/.sharedrc
fi

# To customize prompt, run `p10k configure` to override internal config.
if [[ -f "$HOME/.p10k.zsh" ]]; then
  source "$HOME/.p10k.zsh"
elif [[ -s "${ZDOTDIR:-$HOME}/.zprezto/p10k.zsh" ]]; then
  # Fall back to internal p10k configuration.
  source "${ZDOTDIR:-$HOME}/.zprezto/p10k.zsh"
fi

